CREATE TABLE IF NOT EXISTS `ShazamSongs` (
    `id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `song_key` VARCHAR(255) NOT NULL,
    `artist` VARCHAR(255) NOT NULL,
    `title` VARCHAR(255) NOT NULL,
    `image_url` VARCHAR(255),
    `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `modified` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE(`artist`, `title`) 
);